# Generated by Django 4.2.20 on 2025-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('input1', models.CharField(max_length=50)),
                ('input2', models.CharField(max_length=50)),
                ('input3', models.CharField(max_length=50)),
                ('input4', models.CharField(max_length=50)),
                ('input5', models.CharField(max_length=50)),
            ],
        ),
    ]
