# Generated by Django 4.2.20 on 2025-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('users', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('qr', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('failure', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=50)),
                ('component_status', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('component_repaired', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
